apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mission-deployment
spec:
  selector:
    matchLabels:
      app: mission
  replicas: 2 
  template:
    metadata:
      labels:
        app: mission
    spec:
      containers:
        - name: mission
          image: tdk785/m-app:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 


---

apiVersion: v1 
kind: Service 
metadata: 
  name: mission-svc
spec:
  selector:
    app: mission
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 
  type: LoadBalancer 
